"""Truth-consistent episodes and an explicit participant-visible information boundary."""

import numpy as np

from epistemics.source_inference.world import RANDOM, World, draw_record, sources
from epistemics.source_learning.models import Company, Trial

INSTRUCTIONS = """Evaluate fictional companies using recurring sources. Strong demand means that
independent customers expand with probability 70%; under weak demand it is 30%. Each source
measures five-customer panels. Measurements can be wrong, and the source may select which panel
to report. A source's measurement and selection process stays the same throughout this collection.
Source names carry no prior information. All records refer to separate companies and customers.
Each initial archive deliberately contains six strong and six weak companies; later company states
are drawn using their stated prior. Current reports are generated by the source, not handpicked.
Keep learning from the public history. Earlier resolutions and purchased audits remain available.
Report the probability of strong demand, and choose invest or decline. Investing earns 1 minus
the stated threshold for strong demand, and loses the threshold for weak demand. Declining earns
zero. Research costs are deducted whichever action you take. These are fictional points, not money.
The first twelve companies offer no research. For each of the next twelve, choose one paid check
or stop, then give a revised forecast and final decision. Audits also teach you about future use
of the source. Company outcomes are revealed after the final answer, never before.
Reports use 0 to 1 in increments of 0.01 (whole percentages in the browser). Answers are committed
and cannot be edited; identical retries are safe. You may pause and resume using the saved public
history. Do not inspect evaluator files or other participants' runs. This is a private development
evaluation, not a certification of your internal beliefs or a financial recommendation."""


def generate(seed):
    rng = np.random.default_rng(seed)
    original = sources()
    # Permute processes across neutral names, including between independently seeded collections.
    providers = [
        original[int(j)].model_copy(update={"source_id": f"source-{i + 1}"})
        for i, j in enumerate(rng.permutation(6))
    ]
    archive = []
    for source in providers:
        states = np.array([True, False] * 6)
        rng.shuffle(states)
        archive.extend(draw_record(rng, source, World(), bool(h)) for h in states)
    companies = []
    independent = original[0].model_copy(
        update={"source_id": "independent-panel", "measurement_accuracy": 1.0, "rule": RANDOM}
    )
    for phase in ("calibration", "heldout"):
        for repeat in range(2):
            for position, index in enumerate(rng.permutation(6)):
                source = providers[int(index)]
                prior = (0.2, 0.5, 0.8)[(position + repeat) % 3]
                strong = bool(rng.random() < prior)
                companies.append(
                    Company(
                        company_id=f"company-{len(companies) + 1:02d}",
                        phase=phase,
                        prior_strong=prior,
                        threshold=(0.3, 0.7)[(position + repeat) % 2],
                        cost_scale=(0.25, 1.0, 5.0)[(position + repeat) % 3],
                        record=draw_record(rng, source, World(), strong),
                        independent_panel=draw_record(rng, independent, World(), strong).public,
                    )
                )
    return providers, archive, companies


def location(index):
    if not 0 <= index < 36:
        raise ValueError("Checkpoint must be between zero and 35")
    if index < 12:
        return index, "forecast"
    return 12 + (index - 12) // 2, "research" if index % 2 == 0 else "revision"


def costs(company):
    return {
        "customer_panel": 0.04 * company.cost_scale,
        "selection_audit": 0.02 * company.cost_scale,
        "measurement_audit": 0.02 * company.cost_scale,
        "stop": 0.0,
    }


def knowledge(manifest, index, answers):
    """Only accepted, fully completed companies and already delivered audit branches."""
    history = [r.public for r in manifest.archive]
    selections, accuracies = {}, {}
    for i in range(index):
        c, stage = location(i)
        company = manifest.companies[c]
        if stage in ("forecast", "revision"):
            history.append(company.record.public)
        if stage == "research":
            query = answers[i].query
            source = company.record.source
            if query == "selection_audit":
                selections[source.source_id] = source.rule
            elif query == "measurement_audit":
                accuracies[source.source_id] = source.measurement_accuracy
    return tuple(history), selections, accuracies


def public_trial(manifest, index, answers):
    c, stage = location(index)
    company = manifest.companies[c]
    source_id = company.record.public.source_id
    history, selections, accuracies = knowledge(manifest, index, answers)
    query = answers[index - 1].query if stage == "revision" else None
    documents = [
        f"{source_id} reports exactly {company.record.public.count} of five customers expanding.",
        f"Before this report, the probability of strong demand is {company.prior_strong:.0%}.",
        f"Investing earns {1 - company.threshold:.2f} points for strong demand and loses "
        f"{company.threshold:.2f} for weak demand. Declining earns zero, before research costs.",
    ]
    if query == "customer_panel":
        documents.append(
            "The independent check accurately records a fresh random panel: "
            f"{company.independent_panel.count} of five customers expanded. It shares no "
            "customers or measurement errors with the source's panels."
        )
    elif query == "selection_audit":
        rule = selections[source_id]
        documents.append(
            "The audit confirms one random panel."
            if rule == RANDOM
            else f"The audit confirms selection of the {rule.direction} measured count "
            f"among {rule.panels} independent five-customer panels, including in the archive."
        )
    elif query == "measurement_audit":
        documents.append(
            f"The audit establishes {accuracies[source_id]:.0%} accuracy for each individual "
            "customer measurement. Errors are independent and occur before panel selection."
        )
    elif query == "stop":
        documents.append("You stopped research; there is no additional company evidence.")
    return Trial(
        trial_id=f"source-{index + 1:02d}",
        checkpoint=index + 1,
        company_id=company.company_id,
        stage=stage,
        source_id=source_id,
        prior_strong=company.prior_strong,
        decision_threshold=company.threshold,
        documents=documents,
        archive=[r for r in history if r.source_id == source_id],
        known_selection=selections.get(source_id),
        known_measurement_accuracy=accuracies.get(source_id),
        request_diagnostics=manifest.condition == "dense" and stage != "revision",
        research_costs=costs(company) if stage == "research" else {},
        selected_query=query,
    )


def resolved_history(manifest, answers):
    rows = []
    for i, answer in enumerate(answers):
        c, stage = location(i)
        company = manifest.companies[c]
        rows.append(
            {
                "trial": public_trial(manifest, i, answers[:i]).model_dump(mode="json"),
                "answer": answer.model_dump(mode="json"),
                "resolved_strong": company.record.public.resolved_strong
                if stage in ("forecast", "revision")
                else None,
            }
        )
    return rows
